### ISSUE TITLE
My real mailbox can't receive your verification code!Please help!

### ISSUE THREAD

**Issue by a1489632** [DigitalPlatDev/US.KG-Issues#1]
I want to migrate my registered account to my real email address, but my real email address always fails to receive your verification email.

Please help! I tried so many times, but it didn't work! It's not in the spam box either!

I tried three real mailboxes and couldn't receive the verification email! I really couldn't help it, so I used a temporary mailbox to register! 
I apologize here.

Thank you very much!

My real email address is a1489632@proton.me   
The temporary email address is zpogersbiu@iubridge.com

**Comment by EdwardLab** [comment]
Did you try another mail?

**Comment by a1489632** [comment]
> Did you try another mail?

Microsoft Outlook: Failed
Protonmail: Failed
Tutamail: Failed
Even some temporary email addresses cannot receive emails!

**Comment by EdwardLab** [comment]
We know outlook can't get email but we believe that's outlook issue we don't know how to fix this

**Comment by a1489632** [comment]
> We know Outlook can't receive emails, but we believe it's an Outlook issue, and we're not sure how to fix it.

But it's not just Outlook. I tried all the email addresses I could register for, but I couldn't receive any of your emails. However, I was able to receive emails from others. Your email system compatibility is too bad.

**Comment by EdwardLab** [comment]
We've switched to Amazon SES for sending registration verification emails. I think is works now

**Comment by EdwardLab** [comment]
this is issue is fixed, I will close it
