### ISSUE TITLE
US.KG Panel Issue

### ISSUE THREAD

**Issue by MyOnee** [DigitalPlatDev/US.KG-Issues#10]
**Describe the bug, issue, or problem:**  
Hi, thank you for providing a place to provide issues. I can't create a panel account, and I have created issues several times, and the results are still the same. I have given stars for a long time, but the results are the same. Please fix this error.

**URL (if applicable):**  
https://github.com/DigitalPlatDev/US.KG/issues

**Domain Name (if applicable):**  
---

**Expected Behavior:**  
---

**Screenshots:**  
....
![Screenshot_20240822_185414_Chrome Dev](https://github.com/user-attachments/assets/4db1dea1-c9c4-46f4-9ba0-922d6c5334c1)
![Screenshot_20240822_185810_Chrome Dev](https://github.com/user-attachments/assets/d7bfad97-92e2-4381-bfab-b4bf41856ccf)

**Additional Context:**  
FIX THIS BUG PLEASE :)

**Comment by EdwardLab** [comment]
This problem may be caused by your activity is private. I have approved it, just log in :)
