### ISSUE TITLE
US.KG Panel Issue

### ISSUE THREAD

**Issue by Twddhcm** [DigitalPlatDev/US.KG-Issues#13]
**Describe the bug, issue, or problem:**  
Unable to register domain name

**Domain Name (if applicable):**  
mmk.us.kg

**Expected Behavior:**  
I want to register this domain name and bind it to my account

**Screenshots:**  

**Additional Context:**  
Whois：This domain name is not registered, you can register it on https://nic.us.kg!
register：Sorry, this domain name is already registered

Account ID:269230910

**Comment by EdwardLab** [comment]
If this is no longer an issue I will close it
