### ISSUE TITLE
new user login issue

### ISSUE THREAD

**Issue by foxsheep** [DigitalPlatDev/US.KG-Issues#15]
**Describe the bug, issue, or problem:**  
unable to login after registeration, verification and github KYC aprroved.
Incorrect username or password when login with email and password.
This user is not registered when try to reset password.

**URL (if applicable):**  
Do not upload sensitive private content (such as URLs containing account information).

**Domain Name (if applicable):**  
Example: example.us.kg

**Expected Behavior:**  
Describe clearly what you expected to happen.

**Screenshots:**  

**Additional Context:**  
Add any other relevant information about the problem here.

**Comment by EdwardLab** [comment]
Please provide your username

**Comment by foxsheep** [comment]
> Please provide your username

username: foxsheep

**Comment by foxsheep** [comment]
It seems us.kg has no username dulplication check on registration.
now I got a new username and it works fine.
