### ISSUE TITLE
US.KG Panel Issue

### ISSUE THREAD

**Issue by MyNameIsDark01** [DigitalPlatDev/US.KG-Issues#16]
**Describe the bug, issue, or problem:**  
Site not working and also domains

**URL (if applicable):**  
https://nic.us.kg/

**Expected Behavior:**  
it should open the US.KG site

![image](https://github.com/user-attachments/assets/aa63bc2d-6c66-4357-9e1b-0e436fef16d7)

**Comment by gablilli** [comment]
Hi, I'm also italian, but I can reach us.kg sites, did you check your dnses? What's your ISP? I'm actually under Vodafone and everything's working.

**Comment by MyNameIsDark01** [comment]
Solved

Il giorno gio 5 set 2024 alle ore 21:21 gablilli ***@***.***>
ha scritto:
