### ISSUE TITLE
US.KG小组问题

### ISSUE THREAD

**Issue by fjhkkk** [DigitalPlatDev/US.KG-Issues#23]
**Describe the bug, issue, or problem:**  
Verify my KYC

**URL (if applicable):**  
Do not upload sensitive private content (such as URLs containing account information).

**Domain Name (if applicable):**  
Example: example.us.kg

**Expected Behavior:**  
I donated $1.08 to verify KYC.

**Screenshots:**  
![IMG_0779](https://github.com/user-attachments/assets/92fb16d2-06ca-4183-bc0d-74cf1ad77586)

**Additional Context:**  
Add any other relevant information about the problem here.

**Comment by EdwardLab** [comment]
Done!
