### ISSUE TITLE
reCAPTCHA failed, Please back and login again!

### ISSUE THREAD

**Issue by fgr178707** [DigitalPlatDev/US.KG-Issues#25]
**Describe the bug, issue, or problem:**  
Passed reCAPTCHA and won't let you log in.

**Expected Behavior:**  
log in frequently

**Screenshots:**  

![image](https://github.com/user-attachments/assets/de306c00-5c2a-450e-88ba-882c6796cb7c)
![image](https://github.com/user-attachments/assets/2b503d9e-cd44-4d09-aa9d-e0263741a53d)

**Comment by EdwardLab** [comment]
Since Google has adjusted the free CAPTCHA quota, it has reached the upper limit and we need to manually migrate to other CAPTCHA service providers.

{'success': False, 'error-codes': ['Over Enterprise free quota. Please ensure your project has an active billing account: https://cloud.google.com/recaptcha-enterprise/billing-information']%7D

**Comment by fgr178707** [comment]
> 由于 Google 调整了免费 CAPTCHA 额度，已经达到上限，我们需要手动迁移到其他 CAPTCHA 服务提供商。
> 
> {'success'： false， 'error-codes'： ['超过企业免费配额。请确保您的项目具有有效的计费帐户：https：//cloud.google.com/recaptcha-enterprise/billing-information']%7D

Try the cloudflare captcha service

**Comment by EdwardLab** [comment]
This issue has been temporarily fixed and will be switched to another Captcha in the near future

**Comment by fgr178707** [comment]
> This issue has been temporarily fixed and will be switched to another Captcha in the near future

desirable

I have one more question.
If I don't renew my domain name when it expires, will it be reclaimed or frozen?
A domain recall means I have to re-register the domain
Freeze means I don't need to re-register it, just renew it

**Comment by EdwardLab** [comment]
Just click renew button, no need re register

**Comment by fgr178707** [comment]
> Just click renew button, no need re register

desirable

**Comment by WHHHHHHHA** [comment]
> ，已经达到上限，我们需要手动迁移到其他 CAPTCHA 服务提供商。
> 
> {'success'： false， 'error-codes'： ['超过企业免费配额。请确保您的项目具有有效的计费帐

我今天还是遇到了这个提示,是还没有切换吗

**Comment by fgr178707** [comment]
> Try the cloudflare captcha service

#29
