### ISSUE TITLE
US.KG Panel Issue

### ISSUE THREAD

**Issue by khanji-ideas** [DigitalPlatDev/US.KG-Issues#29]
**Describe the bug, issue, or problem:**  
Provide a clear and concise description of the bug or problem and steps to reproduce it.
ReCaptcha free quota exceeded

**URL (if applicable):**  
Do not upload sensitive private content (such as URLs containing account information).
https://register.us.kg/auth/login

**Expected Behavior:**  
Describe clearly what you expected to happen.
I expected the recaptcha to work properly
**Screenshots:**  
![Screenshot 2024-10-14 125352](https://github.com/user-attachments/assets/5d0281f4-3942-44aa-849b-35e710407141)

**Additional Context:**  
Add any other relevant information about the problem here.
I suggest making a server-side php captcha server. 
Code can be found at https://www.html-code-generator.com/php/captcha-image-code-generator

**Comment by fgr178707** [comment]
@EdwardLab Not again.
Migrating authentication to cloudflare

**Comment by EdwardLab** [comment]
Thank you for your feedback, this issue has now been fixed
