### ISSUE TITLE
US.KG Panel Issue

### ISSUE THREAD

**Issue by NOXX0665** [DigitalPlatDev/US.KG-Issues#3]
**Describe the bug, issue, or problem:**  
After passing my KYC verifying, when trying to access the panel, it shows the manu asking me to do the KYC verification.

**URL (if applicable):**  
https://register.us.kg/

**Domain Name (if applicable):**  
Not applicable

**Expected Behavior:**  
Access to the panel or a menu to register a domain name

**Screenshots:**  
![image](https://github.com/user-attachments/assets/9640db99-39d7-4940-a137-d3c5b099011b)

**Additional Context:**  
None

**Comment by EdwardLab** [comment]
Which method do you use to conduct KYC?

**Comment by NOXX0665** [comment]
I used the Github method, I was verified. Here is the link to that issue : https://github.com/DigitalPlatDev/US.KG/issues/4882#issuecomment-2284969089

**Comment by NOXX0665** [comment]
The issue if fixed, i had to make another KYC request because i had added a space before my email address in the issue title. Thank you for the help!
