### ISSUE TITLE
The account can't be logged in

### ISSUE THREAD

**Issue by HEXIkx** [DigitalPlatDev/US.KG-Issues#30]
The account can't be logged in
3550169631@qq.com

![Screenshot_20241016_135011](https://github.com/user-attachments/assets/16f83d73-83c2-419a-834d-aa4df255f04f)

**Comment by EdwardLab** [comment]
How can I reproduce this pls?

**Comment by EdwardLab** [comment]
Problem still exists?

**Comment by EdwardLab** [comment]
If this no longer a problem I'll close this
