### ISSUE TITLE
US.KG Panel Issue: reCAPTCHA fail during login

### ISSUE THREAD

**Issue by chrisyuancn** [DigitalPlatDev/US.KG-Issues#31]
**Describe the bug, issue, or problem:**  

Error!
reCAPTCHA failed, Please back and login again!{'success': False, 'error-codes': ['Over Enterprise free quota. Please ensure your project has an active billing account: https://cloud.google.com/recaptcha-enterprise/billing-information']}

**Comment by EdwardLab** [comment]
Okay, I'll fix it later

**Comment by EdwardLab** [comment]
Thank you for your feedback, this issue has now been fixed
