### ISSUE TITLE
US.KG Panel Issue

### ISSUE THREAD

**Issue by AIVSR** [DigitalPlatDev/US.KG-Issues#33]
**Describe the bug, issue, or problem:**  
Using Outlook account login failed and prompted reCAPTCHA failed.

Detail：
reCAPTCHA failed, Please back and login again!{'success': False, 'error-codes': ['Over Enterprise free quota. Please ensure your project has an active billing account: https://cloud.google.com/recaptcha-enterprise/billing-information']}

**Comment by EdwardLab** [comment]
Thank you for your feedback, this issue has now been fixed
