### ISSUE TITLE
US.KG Panel Issue

### ISSUE THREAD

**Issue by Sam2368** [DigitalPlatDev/US.KG-Issues#4]
**Describe the bug, issue, or problem:**  
The Login button on the Login Form does not work you have to use google sign-in to login 

**URL (if applicable):**  
[register.kg.us](https://register.us.kg/auth/login?next=%2F)

**Domain Name (if applicable):**  

**Expected Behavior:**  
I expected to be able to login after clicking the login button on the authentication page

**Screenshots:**  

**Additional Context:**  
I had to use google sso for which i did not use to create the account and it worked.

**Comment by EdwardLab** [comment]
why "not work" please describe the problem in detail

**Comment by EdwardLab** [comment]
Can you try another browser? Make sure that you filled email and password

**Comment by EdwardLab** [comment]
Can you provide screenshot?

**Comment by Sam2368** [comment]
I tried other browsers, still the same, the details are correct but when
you click login nothing happens

**Comment by Sam2368** [comment]
Login button now works, guess the captcha was the problem could you add an
option for another captcha, maybe solvemedia or cloudflare. Thanks in
advance.

**Comment by EdwardLab** [comment]
No problem for me. I guess your ISP is blocking the CAPTCHA. We won't make changes based on a small group of users. If this is the case, you should use a proxy or VPN.

**Comment by Sam2368** [comment]
Ok, thanks.
