### ISSUE TITLE
Request to Change Account Email and Reset Password

### ISSUE THREAD

**Issue by fandesk** [DigitalPlatDev/US.KG-Issues#40]
Hello,

I am experiencing an issue with accessing my us.kg account because the email I used for registration has been deactivated after I graduated. Here are the details of my situation:

1. I registered my us.kg account using my school email, which is no longer active.
2. As a result, I am unable to receive the password reset email and have forgotten my password.
3. I have a registration link saved in my browser history that includes a valid token from when I initially registered, which can confirm my prior access to the account.
4. Additionally, I have documents that can verify my previous ownership of the school email.

I am not certain if it is appropriate to submit this request through a bug report issue, but I was unable to find any other contact method. Given this, I kindly request assistance in updating my account email to a new address and providing a way to reset my password. Please let me know if you require any further information to verify my identity and account ownership.

Thank you for your help.

**Comment by duckopia** [comment]
First: Go to "My Account" tab.
![image](https://github.com/user-attachments/assets/2a2d08b9-66e3-46d1-b9aa-a675e1bbf589)
Then, you can see and change your email.
![image](https://github.com/user-attachments/assets/c5bb9c30-53d2-4638-a3d6-21a6ac052419)

**Comment by duckopia** [comment]
Hope this helpful for you😄

**Comment by duckopia** [comment]
Contact to admin if you need more help
contact@nic.us.kg

**Comment by EdwardLab** [comment]
If it's still a problem, could you provide your KYC information, or any information as much as possible so that we can confirm that the account is yours, please send it to us via email. Thank you

**Comment by fandesk** [comment]
Thank you for your response. I’ve sent an email to ***@***.***,
please check it.

**Comment by EdwardLab** [comment]
closed since I already changed
