### ISSUE TITLE
US.KG Panel Issue

### ISSUE THREAD

**Issue by quyasp** [DigitalPlatDev/US.KG-Issues#41]
The issue title cannot be deleted. Can you please help delete the email that was submitted during registration? This is to ensure privacy. Thank you!

**Comment by aikooo7** [comment]
> The issue title cannot be deleted. Can you please help delete the email that was submitted during registration? This is to ensure privacy. Thank you!

Do you mean whois privacy? https://en.m.wikipedia.org/wiki/Domain_privacy

**Comment by quyasp** [comment]
> > 问题标题无法删除。您能帮忙删除注册时提交的邮箱吗？这是为了保护隐私。谢谢！
> 
> 你是指 whois 隐私吗？https://en.m.wikipedia.org/wiki/Domain_privacy

I am referring to the emails related to the GitHub KYC verification submitted during the registration on us.kg, which seem to be deletable only by an administrator.

**Comment by quyasp** [comment]
> > The issue title cannot be deleted. Can you please help delete the email that was submitted during registration? This is to ensure privacy. Thank you!
> 
> Do you mean whois privacy? https://en.m.wikipedia.org/wiki/Domain_privacy

I am referring to the email associated with GitHub KYC verification, which seems to only be removable by an administrator.

**Comment by aikooo7** [comment]
> > > The issue title cannot be deleted. Can you please help delete the email that was submitted during registration? This is to ensure privacy. Thank you!
> > 
> > Do you mean whois privacy? https://en.m.wikipedia.org/wiki/Domain_privacy
> 
> I am referring to the email associated with GitHub KYC verification, which seems to only be removable by an administrator.

See this link on how to remove confidential information from a issue, I hope this helps:

https://stackoverflow.com/questions/69755177/how-to-remove-sensitive-information-from-issue-history-on-github

**Comment by quyasp** [comment]
> > > > The issue title cannot be deleted. Can you please help delete the email that was submitted during registration? This is to ensure privacy. Thank you!
> > > 
> > > 
> > > Do you mean whois privacy? https://en.m.wikipedia.org/wiki/Domain_privacy
> > 
> > 
> > I am referring to the email associated with GitHub KYC verification, which seems to only be removable by an administrator.
> 
> See this link on how to remove confidential information from a issue, I hope this helps:
> 
> https://docs.github.com/en/communities/moderating-comments-and-conversations/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history

Thank you, but the previous KYC template required the email address to be included in the title. Any changes to the title will still be recorded. Therefore, I'm asking the warehouse owner if it can be removed.

**Comment by EdwardLab** [comment]
Yes, please send issue link so I can delete it, thank you!

**Comment by quyasp** [comment]
> Yes, please send issue link so I can delete it, thank you!

https://github.com/DigitalPlatDev/FreeDomain/issues/13376
Thank you.

**Comment by EdwardLab** [comment]
No problem. I have deleted it
