### ISSUE TITLE
Verification saying "You haven't starred our repository" when I have

### ISSUE THREAD

**Issue by SlimyFrog123** [DigitalPlatDev/US.KG-Issues#42]
I have applied 3 or 4 times now, creating an issue, but every time I get this response:
![image](https://github.com/user-attachments/assets/cc840148-826c-430a-8d35-9bc95a04a5e6)

I have starred it (even tried un-starring and re-starring it), here is proof:
![image](https://github.com/user-attachments/assets/b04ffbe3-c3e0-407a-b42f-d38db5d8a72e)

I have seen this happen to other users' requests, as well.

**Comment by EdwardLab** [comment]
Oh sorry that's bad just send me username pls

**Comment by SlimyFrog123** [comment]
My username is: SlimyFrog123

**Comment by EdwardLab** [comment]
Okay I approved

**Comment by SlimyFrog123** [comment]
Thank you!

Looking at previous issues, it seems like everyone is having the same problem, so just be aware that this is an issue. 👍

**Comment by EdwardLab** [comment]
Oh gosh thanks for your reminder, I changed the repository name, so this is indeed an issue
