### ISSUE TITLE
Request to change email

### ISSUE THREAD

**Issue by xtexChooser** [DigitalPlatDev/US.KG-Issues#43]
I registered an account with email address `xtexchooser@duck.com`.
I am glad to donate for KYC, however, per PRC laws, citizens under the age of 18 could not have owned bank cards.
Therefore, I cordially request to change my email address to `xtexchooser@gmail.com` to use GitHub KYC.
Thanks for your patience!

**Comment by EdwardLab** [comment]
Please send change mail request with email xtexchooser@duck.com to contact@digitalplat.org to prove that it was you who requested the action, I will close it. Thank you.
