### ISSUE TITLE
Request to delete the registered account, because there is no place to delete in the settings

### ISSUE THREAD

**Issue by 1264151413** [DigitalPlatDev/US.KG-Issues#44]
Request to delete the registered account, because there is no place to delete in the settings.
Because I registered with the email address, I just wanted to test it. After I registered, I just wanted to see if I could delete the account. I found that in the settings, I looked everywhere and found that there seemed to be no way to delete the account.
I now want to delete the account I have currently registered. Is there any solution?

**Comment by 1264151413** [comment]
First of all, I don't really believe in the security of QQ mailbox, but I plan to make a tutorial video, and there may be some people in inland China. They are inside the Great Firewall, and most people may use QQ mailbox, so I plan to have a part in the tutorial video where they use QQ mailbox to register an account. And I just wanted to register myself before starting to record to see if it is successful. Now that the registration is successful, I need to restore to my initial state without a registered account, so that it will be convenient for me to start recording the tutorial video. So, could you please tell me how to delete the account or help me delete the account I have already registered?

**Comment by EdwardLab** [comment]
Yes, just open https://register.us.kg/user/request_delete

Then your account and all domains will be deleted!! 
Make sure you logged, and open this url
This action cannot be undone
