### ISSUE TITLE
US.KG KYC verification problem

### ISSUE THREAD

**Issue by Leffler25** [DigitalPlatDev/US.KG-Issues#45]
**Describe the bug, issue, or problem:**  
Provide a clear and concise description of the bug or problem and steps to reproduce it.
When I used KYCJ to verify the US.KG domain, it failed to verify. It showed that it had not been starred, but in fact it had been starred. I would like to ask if this is a problem with the review or my GitHub account. Please explain. Thank you!
**Expected Behavior:**  
Describe clearly what you expected to happen.
Make my KYC verification pass normally

**Comment by sqcsl-dev** [comment]
I'm facing the same issue as well.

**Comment by EdwardLab** [comment]
? provide issue link please
