### ISSUE TITLE
"The domain name has already been registered, or this domain name is reserved, or it is unavailable.

### ISSUE THREAD

**Issue by treeentertainment** [DigitalPlatDev/US.KG-Issues#5]
**Describe the bug, issue, or problem:**  
I want to register pl.us.kg but It says it is unavailable

**URL (if applicable):**  
pl.us.kg
**Domain Name (if applicable):**  
pl.us.kg

**Expected Behavior:**  
make it available please...

**Screenshots:**  
no Screenshots

**Additional Context:**  
no Additional Context:

**Comment by EdwardLab** [comment]
At least 3 letters, "pl" only 2 letters
