### ISSUE TITLE
US.KG Panel Issue

### ISSUE THREAD

**Issue by treeentertainment** [DigitalPlatDev/US.KG-Issues#50]
**Describe the bug, issue, or problem:**  
Some domains are not available

**URL (if applicable):**  
https://register.us.kg/panel/register

**Domain Name (if applicable):**  
tree.us.kg

**Expected Behavior:**  
I want to register it

**Screenshots:**  
![image](https://github.com/user-attachments/assets/e83469a9-15a6-40a1-9a91-02f6a8fe9e80)
![image](https://github.com/user-attachments/assets/b5dc7211-3e0b-45c0-9569-fcfac919a46e)
![image](https://github.com/user-attachments/assets/9ecbf734-1b54-41b3-87a0-a77badc8b009)

**Additional Context:**

**Comment by EdwardLab** [comment]
This domain is not available. Please consider another name, I will close this issue.
