### ISSUE TITLE
US.KG Panel Issue

### ISSUE THREAD

**Issue by Alphawolf072** [DigitalPlatDev/US.KG-Issues#53]
**Describe the bug, issue, or problem:**  
After receiving the approval notice and click to redirect to us.kg main panel webpage, but the webpage does not seems ok. unable to click any items on main panel except for "donation" 

Please see sceenshots
![屏幕截图 2024-11-16 183607](https://github.com/user-attachments/assets/74779c48-3bc3-4d10-9f90-d70de8854d6a)

![屏幕截图 2024-11-16 183620](https://github.com/user-attachments/assets/c6d6ef46-d0ec-4e9a-9f32-cf07df5226ac)

please advise

**Comment by EdwardLab** [comment]
This is screenshot... Go to https://register.us.kg
