### ISSUE TITLE
US.KG Panel Open in New Tab Fullscreen "error"

### ISSUE THREAD

**Issue by treeentertainment** [DigitalPlatDev/US.KG-Issues#6]
**Describe the bug, issue, or problem:**  
full screen dosen't works in microsoft browser "edge" (sometimes), and other browsers too

**URL (if applicable):**  
https://register.us.kg/panel/main#

**Domain Name (if applicable):**  

**Expected Behavior:**  
https://www.w3schools.com/howto/howto_js_fullscreen.asp

check this please

**Screenshots:**  
![image](https://github.com/user-attachments/assets/da6c8dd4-4b94-4232-b70a-1bdd3eb52d0a)

https://github.com/user-attachments/assets/8ce6346a-2a61-45d5-b531-552b6c5a9639

**Additional Context:**

**Comment by treeentertainment** [comment]
> **Describe the bug, issue, or problem:** full screen dosen't works in microsoft browser "edge" (sometimes)
> 
> **URL (if applicable):** https://register.us.kg/panel/main#
> 
> **Domain Name (if applicable):**
> 
> **Expected Behavior:** https://www.w3schools.com/howto/howto_js_fullscreen.asp
> 
> check this please
> 
> **Screenshots:** ![image](https://private-user-images.githubusercontent.com/160602348/358810101-da6c8dd4-4b94-4232-b70a-1bdd3eb52d0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NTU4NzgsIm5iZiI6MTcyMzk1NTU3OCwicGF0aCI6Ii8xNjA2MDIzNDgvMzU4ODEwMTAxLWRhNmM4ZGQ0LTRiOTQtNDIzMi1iNzBhLTFiZGQzZWI1MmQwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwNDMyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzcxYWEzNTBmNjBmZDFlZWE0OTY5ODFmZGQyYTcxOGIyOTAxZDg3NGI2OTc3MDU3MTk5OGMyODAwM2ZkOWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6lvezUZzxv_DtVR4enBIRCQdoIw4YwSaIp9coG5KrOE)
> 
>  checkout.mp4 
> **Additional Context:**

**Comment by EdwardLab** [comment]
You clicked "New Tab" instead of "Fullscreen"

**Comment by treeentertainment** [comment]
oh, thanks
