### ISSUE TITLE
FEATURE REQUEST NOT A BUG: Add DNSSEC support

### ISSUE THREAD

**Issue by aikooo7** [DigitalPlatDev/US.KG-Issues#7]
Hi, us.kg is really impressive and the last equivelant was the eu.org service so I am thankfull for it but I think it can always be better. DNSSEC requires a DS record in the registrar, could that be possible to implement?

**Comment by EdwardLab** [comment]
yes adding DNSSEC support is in our future plans.

**Comment by aikooo7** [comment]
> yes adding DNSSEC support is in our future plans.

Alright then, thanks, I will be going in this issue time time to to check it.

**Comment by EdwardLab** [comment]
I will close it, this is the future plan
