### ISSUE TITLE
Request GitHub KYC-GaoYuan522

### ISSUE THREAD

**Issue by GaoYuan522** [DigitalPlatDev/US.KG-Issues#76]
### KYC Using Your GitHub Account

Please make sure your GitHub account meets the following requirements (all are required):

- [x] The issue title must be: Request GitHub KYC - Your US.KG Panel registered username. This ensures our automated script can detect your registered username. (For example, your title should be: Request GitHub KYC-example)

- [x] This is not a new GitHub account; it has existing repositories and stars.

- [x] This is my first US.KG NIC Panel account.

- [x] I promise not to use the domain name for criminal or abusive purposes.

- [x] Please star this repository, This will let more people know about this project!

**Your Account Details (US.KG NIC Panel):**

Please fill out the following information; otherwise, your request will not be processed:

- Username: GaoYuan522

- Reason for Registering the .US.KG Domain Name (Why):I am lenrning how to build a website,and want to build a vlog.

**Comment by GaoYuan522** [comment]
@EdwardLab @Thedustye I have met all the requirements, please approve, I hope to learn to build your own website.

**Comment by Thedustye** [comment]
你好。已收到你的邮件，我会在假期结束后尽快处理。————————————这是来自QQ邮箱的自动回复邮件。

**Comment by GaoYuan522** [comment]
Anyone here？@EdwardLab

**Comment by EdwardLab** [comment]
Submit in DigitalPlatDev/FreeDomain not here
