### ISSUE TITLE
US.KG Panel Issue

### ISSUE THREAD

**Issue by Srvinhub** [DigitalPlatDev/US.KG-Issues#8]
Primary Name Server Not Listed At Parent

**Comment by EdwardLab** [comment]
If you mean the DNS root servers are not listed, then wait for more than 24 hours

**Comment by Srvinhub** [comment]
“I have bound the us.kg domain to the VLESS proxy created on Cloudflare Workers, but it causes some issues, such as WebSocket connections being instantly blocked. I’m not sure what the problem is.”

在 2024年8月20日，20:16，Edward Hsing ***@***.***> 写道：

﻿

Is this still a issue?
