### ISSUE TITLE
US.KG Registration Issue

### ISSUE THREAD

**Issue by gablilli** [DigitalPlatDev/US.KG-Issues#9]
Hi, I’m new on us.kg and I’d love to use it.
The fact is that the account email confirm isn’t arrived yet. I retried and retried but nothing would happen. Note: I use a gmail email, but even in spam there is nothing. (I also tried with a custom domain email but it didn’t work actually).

**Comment by EdwardLab** [comment]
How long you waited? have you try again later?

**Comment by gablilli** [comment]
I waited 8-9 hours the mail, but it never arrived. And obviously, I tried hours later and even now, but nothing happens.

**Comment by gablilli** [comment]
I retried with a VPN in an another state, and it worked. Thanks anyways for your support!
